### ISSUE TITLE
Is random.sample() appropriate?

### ISSUE THREAD

**Issue by mkgvt** [congma/pass-genphrase#1]
The documentation for random.sample(population, k) says "used for random sampling without replacement". I believe what you want is random sampling *with* replacement. Otherwise the effective entropy of the chosen passphrase is reduced.

Rationale: there are log2(7776) bits of entropy for the first choice, log2(7775) bits of entropy for the second, log2(7774) bits of entropy for the third, etc. (Granted, for a six word passphrase, the difference in entropy would be 78.5489 - 78.5461 = .0028 bits of entropy (or 0.0035%) but I believe sampling with replacement is the correct choice.)

**Comment by congma** [comment]
Good point. I think if we follow closely the original description of "diceware", sampling with is the right one. Thank you!
